#
# Deployment to run cli and for debugging
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli
spec:
  selector:
    matchLabels:
      app: cli
  replicas: 1
  template:
    metadata:
      labels:
        app: cli
    spec:
      containers:
        - name: cli
          image: gcr.io/google-samples/node-hello:1.0
